### ISSUE TITLE
RustPython Contribution

### ISSUE THREAD

**Issue by bongjunj** [gdsc-kaist/2022-2H-Research#1]
프로젝트에 참가하실 멤버분들은 이메일을 남겨주세요

**Comment by yym0329** [comment]
유영민, yym3055@kaist.ac.kr

**Comment by bongjunj** [comment]
# What is a parser?
- Lexical Analysis of Python: https://docs.python.org/3/reference/lexical_analysis.html
- BNF: https://en.wikipedia.org/wiki/Backus–Naur_form
- AST: https://en.wikipedia.org/wiki/Abstract_syntax_tree
- Parser Generator: https://en.wikipedia.org/wiki/LALR_parser_generator

# Related RustPython / CPython modules

- CPython's Parser Implementation: https://github.com/python/cpython/tree/main/Parser
- RustPython's Parser Implementation: https://github.com/RustPython/RustPython/tree/main/compiler/parser

# Ongoing Related Issues/PR

https://github.com/RustPython/RustPython/issues/4265#issue-1437573387

https://github.com/RustPython/RustPython/pull/4257

**Comment by bongjunj** [comment]
Python More Tips: https://github.com/satwikkansal/wtfpython
